package dto;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.util.Objects;

/**
 * {@link Material} specific assertions - Generated by CustomAssertionGenerator.
 */
public class MaterialAssert extends AbstractAssert<MaterialAssert, Material> {

  /**
   * Creates a new <code>{@link MaterialAssert}</code> to make assertions on actual Material.
   * @param actual the Material we want to make assertions on.
   */
  public MaterialAssert(Material actual) {
    super(actual, MaterialAssert.class);
  }

  /**
   * An entry point for MaterialAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myMaterial)</code> and get specific assertion with code completion.
   * @param actual the Material we want to make assertions on.
   * @return a new <code>{@link MaterialAssert}</code>
   */
  public static MaterialAssert assertThat(Material actual) {
    return new MaterialAssert(actual);
  }

  /**
   * Verifies that the actual Material's id is equal to the given one.
   * @param id the given id to compare the actual Material's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Material's id is not equal to the given one.
   */
  public MaterialAssert hasId(int id) {
    // check that actual Material we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    int actualId = actual.getId();
    if (actualId != id) {
      failWithMessage(assertjErrorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Material's name is equal to the given one.
   * @param name the given name to compare the actual Material's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Material's name is not equal to the given one.
   */
  public MaterialAssert hasName(String name) {
    // check that actual Material we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Material's supplier is equal to the given one.
   * @param supplier the given supplier to compare the actual Material's supplier to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Material's supplier is not equal to the given one.
   */
  public MaterialAssert hasSupplier(String supplier) {
    // check that actual Material we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting supplier of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualSupplier = actual.getSupplier();
    if (!Objects.areEqual(actualSupplier, supplier)) {
      failWithMessage(assertjErrorMessage, actual, supplier, actualSupplier);
    }

    // return the current assertion for method chaining
    return this;
  }

}
