package dto;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.util.Objects;

/**
 * {@link OperatorTest} specific assertions - Generated by CustomAssertionGenerator.
 */
public class OperatorTestAssert extends AbstractAssert<OperatorTestAssert, OperatorTest> {

  /**
   * Creates a new <code>{@link OperatorTestAssert}</code> to make assertions on actual OperatorTest.
   * @param actual the OperatorTest we want to make assertions on.
   */
  public OperatorTestAssert(OperatorTest actual) {
    super(actual, OperatorTestAssert.class);
  }

  /**
   * An entry point for OperatorTestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myOperatorTest)</code> and get specific assertion with code completion.
   * @param actual the OperatorTest we want to make assertions on.
   * @return a new <code>{@link OperatorTestAssert}</code>
   */
  public static OperatorTestAssert assertThat(OperatorTest actual) {
    return new OperatorTestAssert(actual);
  }

  /**
   * Verifies that the actual OperatorTest's source is equal to the given one.
   * @param source the given source to compare the actual OperatorTest's source to.
   * @return this assertion object.
   * @throws AssertionError - if the actual OperatorTest's source is not equal to the given one.
   */
  public OperatorTestAssert hasSource(org.assertj.db.type.Source source) {
    // check that actual OperatorTest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting source of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.assertj.db.type.Source actualSource = actual.source;
    if (!Objects.areEqual(actualSource, source)) {
      failWithMessage(assertjErrorMessage, actual, source, actualSource);
    }

    // return the current assertion for method chaining
    return this;
  }

}
