package dto;

import org.assertj.core.api.AbstractAssert;

/**
 * {@link OperatorTest} specific assertions - Generated by CustomAssertionGenerator.
 */
public class OperatorTestAssert extends AbstractAssert<OperatorTestAssert, OperatorTest> {

  /**
   * Creates a new <code>{@link OperatorTestAssert}</code> to make assertions on actual OperatorTest.
   * @param actual the OperatorTest we want to make assertions on.
   */
  public OperatorTestAssert(OperatorTest actual) {
    super(actual, OperatorTestAssert.class);
  }

  /**
   * An entry point for OperatorTestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myOperatorTest)</code> and get specific assertion with code completion.
   * @param actual the OperatorTest we want to make assertions on.
   * @return a new <code>{@link OperatorTestAssert}</code>
   */
  public static OperatorTestAssert assertThat(OperatorTest actual) {
    return new OperatorTestAssert(actual);
  }

}
