package dto;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.util.Objects;

/**
 * {@link Receipt} specific assertions - Generated by CustomAssertionGenerator.
 */
public class ReceiptAssert extends AbstractAssert<ReceiptAssert, Receipt> {

  /**
   * Creates a new <code>{@link ReceiptAssert}</code> to make assertions on actual Receipt.
   * @param actual the Receipt we want to make assertions on.
   */
  public ReceiptAssert(Receipt actual) {
    super(actual, ReceiptAssert.class);
  }

  /**
   * An entry point for ReceiptAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myReceipt)</code> and get specific assertion with code completion.
   * @param actual the Receipt we want to make assertions on.
   * @return a new <code>{@link ReceiptAssert}</code>
   */
  public static ReceiptAssert assertThat(Receipt actual) {
    return new ReceiptAssert(actual);
  }

  /**
   * Verifies that the actual Receipt's id is equal to the given one.
   * @param id the given id to compare the actual Receipt's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Receipt's id is not equal to the given one.
   */
  public ReceiptAssert hasId(int id) {
    // check that actual Receipt we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    int actualId = actual.getId();
    if (actualId != id) {
      failWithMessage(assertjErrorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Receipt's name is equal to the given one.
   * @param name the given name to compare the actual Receipt's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Receipt's name is not equal to the given one.
   */
  public ReceiptAssert hasName(String name) {
    // check that actual Receipt we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

}
